# Generated by Django 5.0.3 on 2024-10-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0006_remove_post_author_remove_comment_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CostomUser',
        ),
    ]
