# Generated by Django 5.0.3 on 2024-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسنده ها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': True, 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='یورزنیم '),
        ),
    ]
