# Generated by Django 5.0.3 on 2024-09-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
